apiVersion: apps/v1
kind: Deployment
metadata:
  name: augury-deployment
spec:
  selector:
    matchLabels:
      app: augury
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: augury
    spec:
      containers:
      - name: augury
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
          - name: "PORT"
            value: "{{ .Values.port }}"
        envFrom:
          - configMapRef:
              name: augury-cm